transformer:
  feature_size_1:
  feature_size_2:
  extractor_name: 'resnet34'
  pretrain: ''
  tr_extractor: TRUE
  num_encoder_layers: 1
  num_decoder_layers: 3
  d_model: 512
  nhead: 8
  dim_feedforward: 1024
  dropout: 0
model_name: 'transformer'
max_seq_len: 300
warmup_steps: 2000
lr_init: 1
lr_min: 0.0001
batch_size: 30
lr_method: 'adam'
lr_scheduler: 'AwesomeScheduler'
device: 'cuda:0'
multi_gpu: True
criterion_method: 'CrossEntropyLoss'
n_epochs: 30
SCST_predict_mode: 'greedy'
SCST_lr: 0.000005
gradient_accumulate_num: 4
beam_width: 5