transformer:
  feature_size_1:
  feature_size_2:
  extractor_name: 'resnet34'
  pretrain: './model_weights/pretrained_resnet34.pth'
  tr_extractor: FALSE
  num_encoder_layers: 10
  num_decoder_layers: 20
  d_model: 512
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.1
model_name: 'transformer'
max_seq_len: 300
warmup_steps: 2000
lr_init: 0.1
lr_max: 0.0006
batch_size: 50
eval_batch_size: 800
lr_method: 'adam'
lr_scheduler: 'AwesomeScheduler'
device: 'cuda:0'
multi_gpu: True
criterion_method: 'CrossEntropyLoss'
n_epochs: 3
SCST_predict_mode: 'greedy'
SCST_lr: 0.000005
gradient_accumulate_num: 4
beam_width: 5
