path_train_root: './'
path_train_data_dir: 'data/prcd_data/'
path_train_img_dir: 'train'
train_annotations_file: 'small_train_set_labels.csv'
path_val_root: './'
path_val_data_dir: 'data/prcd_data/'
path_val_img_dir: 'validate'
val_annotations_file: 'small_val_set_labels.csv'