origin_dir: 'data/origin'
prcd_dir: 'data/prcd_data'
train_labels: 'train_labels.csv'
val_set_labels: 'val_set_labels.csv'
train_set_labels: 'train_set_labels.csv'
val_size: 400000
train_size: -1
build_vocab: TRUE
split_data_set: TRUE
prc_img: TRUE
img_width: 512
img_height: 256
threshold: 50
threads: 16
