origin_dir: 'data/origin'
prcd_dir: '/data/prcd_data'
train_labels: 'train_labels.csv'
val_set_labels: 'val_set_labels.csv'
train_set_labels: 'train_set_labels.csv'
val_size: 100000
train_size: -1
build_vocab: FALSE
split_data_set: TRUE
prc_img: TRUE
img_width: 512
img_height: 256
# The threshold of thresholding, use Otsu if-1
threshold: 50
num_workers: 16
chunk_size: 400
thresholding: FALSE
phology: TRUE
