img2seq:
  img_w: 512
  img_h: 256
  dim_encoder: 512
  dim_decoder: 256
  dim_attention: 512
  dim_embed:
  dropout: 0.1
model_name: 'seq2seq'
lr_init: 0.001
start_decay: 0
end_decay: 10000
end_warm: 100
lr_warm: 0.0001
lr_min: 0.0001
batch_size: 1
lr_method: 'adam'
lr_scheduler: 'CosineAnnealingLR'
device: 'cuda:1'
criterion_method: 'CrossEntropyLoss'
n_epochs: 10
loss_mode: 'SCST'
SCST_predict_mode: 'greedy'