transformer:
  feature_size_1:
  feature_size_2:
  extractor_name: 'resnet34'
  max_seq_len: 300
  tr_extractor: FALSE
  num_encoder_layers: 2
  num_decoder_layers: 4
  d_model: 512
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.2
lr_init: 0.001
start_decay: 0
end_decay: 10000
end_warm: 100
lr_warm: 0.0001
lr_min: 0.0001
batch_size: 40
lr_method: 'adam'
lr_scheduler: 'CosineAnnealingLR'
device: 'cuda:0'
criterion_method: 'CrossEntropyLoss'
n_epochs: 10
loss_mode: ''
SCST_predict_mode: 'greedy'