transformer:
  feature_size_1:
  feature_size_2:
  extractor_name: 'resnet34'
  tr_extractor: FALSE
  num_encoder_layers: 2
  num_decoder_layers: 4
  d_model: 512
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.2
max_seq_len: 300
warmup_steps: 2000
lr_init: 1
lr_min: 0.0001
batch_size: 50
lr_method: 'adam'
lr_scheduler: 'AwesomeScheduler'
device: 'cuda'
criterion_method: 'CrossEntropyLoss'
n_epochs: 10
loss_mode: ''
SCST_predict_mode: 'greedy'
SCST_lr: 0.00001
gradient_accumulate_num: 8
beam_width: 5